name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Go Get
        run: go get -d -u -v ./...

      - name: Go Test
        run: go test ./...

# vim: set ts=2 sts=2 sw=2 et :
